name: plantist
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Core Packages
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3

  # Local Storage
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0

  # Utilities
  path_provider: ^2.1.4
  uuid: ^4.5.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2

  # Authentication
  local_auth: ^2.3.0

  # UI/UX Packages
  flutter_local_notifications: ^17.2.3
  flutter_slidable: ^3.1.1
  flutter_inappwebview: ^6.1.5

  # Calendar Package
  adoptive_calendar: ^0.2.0

dev_dependencies:
  # Development Dependencies
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: any
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  background_color: "#FFFFFF"
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
